import type { TheatreBookingFields } from '../../../types/clinical';

/** Title Case labels for Vericlaim / Endoscopy / A-slip text fields (ICD uppercase). */
export const CLINICAL_DEMO_FIELD_LABELS: Record<string, string> = {
  surname: 'Surname',
  firstName: 'First Name',
  dateOfBirth: 'Date of Birth',
  age: 'Age',
  idNumber: 'ID Number',
  medicalAid: 'Medical Aid',
  medicalAidNumber: 'Medical Aid Number',
  contactNumber: 'Contact Number',
  bed: 'Bed',
  dateOfAdmission: 'Date of Admission',
  admissionDiagnosis: 'Admission Diagnosis',
  icd10Diagnosis: 'ICD-10 Diagnosis',
  procedure: 'Procedure',
  procedureCodes: 'Procedure Codes',
  dateOfProcedure: 'Date of Procedure',
  complications: 'Complications',
  inpatientNotes: 'Inpatient Notes',
  dateOfDischarge: 'Date of Discharge',
  followUpPlan: 'Follow-up Plan',
  dateOfFollowUp: 'Date of Follow-up',
  furtherComment: 'Further Comment',
  dateOfDiscarded: 'Date Discarded',
};

export const THEATRE_BOOKING_LABELS: Record<keyof TheatreBookingFields, string> = {
  surname: 'Surname',
  firstName: 'First Name',
  dateOfBirth: 'Date of Birth',
  age: 'Age',
  sex: 'Sex',
  medicalAid: 'Medical Aid',
  medicalAidNumber: 'Medical Aid Number',
  contactNumber: 'Contact Number',
  urgencyOfBooking: 'Urgency of Booking',
  diagnosis: 'Diagnosis',
  icd10: 'ICD-10',
  plannedProcedure: 'Planned Procedure',
  procedureCodes: 'Procedure Codes',
  consentObtained: 'Consent Obtained',
  consentPdfFileName: 'Consent form',
  consentPdfUploadedAt: 'Consent uploaded at',
  consentPdfSizeBytes: 'Consent file size',
  bookedWithTheatre: 'Booked With Theatre',
  anaesthesiaArranged: 'Anaesthesia Arranged',
  anaesthetistName: 'Anaesthetist',
  assistantArranged: 'Assistant Arranged',
  assistantName: 'Assistant Name',
  status: 'Status',
  dateOfCompletion: 'Date of Completion',
  startTime: 'Start Time',
  endTime: 'End Time',
  weight: 'Weight (kg)',
  height: 'Height (cm)',
  bmi: 'BMI',
  theatreSheetFileName: 'Theatre sheet',
  theatreSheetUploadedAt: 'Theatre sheet uploaded at',
  theatreSheetSizeBytes: 'Theatre sheet file size',
  dateOfPlannedProcedure: 'Date of Planned Procedure',
};

/** Stable column order for detail panels (Object.keys order is not guaranteed). */
export const THEATRE_BOOKING_DETAIL_KEY_ORDER: (keyof TheatreBookingFields)[] = [
  'surname',
  'firstName',
  'dateOfBirth',
  'age',
  'sex',
  'medicalAid',
  'medicalAidNumber',
  'contactNumber',
  'urgencyOfBooking',
  'diagnosis',
  'icd10',
  'plannedProcedure',
  'procedureCodes',
  'consentObtained',
  'consentPdfFileName',
  'bookedWithTheatre',
  'anaesthesiaArranged',
  'anaesthetistName',
  'assistantArranged',
  'assistantName',
  'status',
  'dateOfCompletion',
  'startTime',
  'endTime',
  'weight',
  'height',
  'bmi',
  'theatreSheetFileName',
  'dateOfPlannedProcedure',
];
