import type { ClinicalTemplateDefinition } from './types';
import { docPathForHaloUser, MO_HALO_USER_ID } from './constants';

function mo(id: string, name: string, fields: ClinicalTemplateDefinition['fields']): ClinicalTemplateDefinition {
  return {
    template_id: id,
    name,
    description: '',
    doc_path: docPathForHaloUser(MO_HALO_USER_ID, id),
    fields,
  };
}

/** Bundled Mo/Henk clinical templates (field schemas from Firebase export). */
export const MO_CLINICAL_TEMPLATE_DEFINITIONS: ClinicalTemplateDefinition[] = [
  mo('admission', 'Admission', [
    { key: 'patient_name', description: "Patient's surname, followed by first name, exactly as it should appear on clinical documents. Format: 'Surname, Name'. Example: 'van Rooy, Kaylen'." },
    { key: 'dob', description: "Patient's date of birth in DD-MM-YYYY format. Example: '02-02-2007'." },
    { key: 'medical_aid', description: "Medical aid provider name. Example: 'LA Health'." },
    { key: 'id', description: "South African ID number (13 digits, no spaces). Example: '0702020202082'." },
    { key: 'medical_aid_no', description: "Medical aid membership number as provided by the patient/insurer. Example: '915566050'." },
    { key: 'contact', description: "Primary patient contact number in local format. Example: '021 555 0123' or '082 123 4567'." },
    { key: 'admission_date', description: "Date of admission in DD/MM/YYYY format. Example: '30/05/2025'." },
    { key: 'admission_urgency', description: "Urgency of admission. Use one word such as 'Emergency', 'Urgent', or 'Elective'. Example: 'Emergency'." },
    { key: 'admission_ward_number', description: "Ward and bed/location details as short free text. Example: 'S10' or 'A7 Bed 5'." },
    { key: 'indication', description: 'Brief indication(s) for admission as bullet points (do not use Python list format). Include ICD-10 codes in brackets where applicable.' },
    { key: 'presenting_complaint', description: 'Presenting complaint/history of presenting complaint written in full sentences. Use bullet points only if the doctor uses them in dictation.' },
    { key: 'pmh', description: 'Past medical history only (exclude current complaint, investigations, and treatment). Use bullet points (do not use Python list format).' },
    { key: 'social_hx', description: 'Social history (occupation, schooling, breastfeeding status where relevant, habits).' },
    { key: 'vitals', description: 'Vital signs with correct SI units/medical notation (mmHg, °C, /min, %, room air). Put them all on the same line.' },
    { key: 'examination', description: 'Focused examination findings as concise lines/bullets (do not use Python list format).' },
    { key: 'diagnosis', description: 'Primary working diagnosis (or differentials) as a numbered list with ICD-10 codes in brackets. Do not use Python list format.' },
    { key: 'management_recommendations', description: 'Management plan as bullet points (do not use Python list format). Include procedures, imaging, antibiotics/fluids, and consent status.' },
  ]),
  mo('colonoscopy', 'Colonoscopy', [
    { key: 'patient_name', description: "Capture the patient's full name exactly as dictated, then re-format as 'Surname, Firstname' (do NOT add titles)." },
    { key: 'dob', description: "Patient's date of birth in DD-MM-YYYY format. Example: 29-08-1963." },
    { key: 'medical_aid', description: 'Exact name of the medical-aid scheme. Example: BANKMED.' },
    { key: 'id', description: '13-digit South-African ID number without spaces. Example: 6308290238089.' },
    { key: 'medical_aid_no', description: 'Exact medical-aid membership number as dictated. Example: 512509260.' },
    { key: 'date_endoscopy', description: 'Calendar date of the procedure in DD/MM/YYYY format. Example: 17/04/2025.' },
    { key: 'start_time', description: 'Scope-in time in 24-hour HH:MM format. Example: 19:31.' },
    { key: 'end_time', description: 'Scope-out time in 24-hour HH:MM format. Example: 20:28.' },
    { key: 'endoscopist', description: 'Initials and surname of the endoscopist exactly as dictated. Example: Patel MQ.', default: 'Patel MQ' },
    { key: 'anaesthetist', description: 'Initials and surname of the anaesthetist or procedural sedationist. Example: Odendaal P.' },
    { key: 'endoscopy_type', description: 'Type of endoscopy exactly as dictated (e.g., Colonoscopy, Gastroscopy, Flexible Sigmoidoscopy, ERCP).' },
    { key: 'procedure_codes', description: 'Comma-separated list of RPL procedure codes without explanations. Example: 0257, 0304, 0011, 0018.' },
    { key: 'indication', description: 'Concise reason for the procedure in one sentence. Example: GI bleed with melaena.' },
    { key: 'boston_score', description: "Boston Bowel Prep Score: 'Left; Transverse; Right; Sum'. Example: L3; T3; R3; Sum: 9." },
    { key: 'anus_rectum', description: 'Exact findings for anus and rectum section as dictated. Example: Normal.' },
    { key: 'sigmoid_left_colon', description: 'Findings for sigmoid and left colon exactly as dictated.' },
    { key: 'transverse_colon', description: 'Transverse-colon findings exactly as dictated.' },
    { key: 'right_colon', description: 'Ascending colon and caecum findings exactly as dictated.' },
    { key: 'ileum', description: 'Ileal findings including whether intubated.' },
    { key: 'biopsies', description: 'Samples sent for pathology or microbiology. If none, type Not done.' },
    { key: 'diagnosis', description: 'Primary and secondary endoscopic diagnoses without codes; Title Case; separate with semicolons.' },
    { key: 'icds', description: 'Most relevant ICD-10 codes only, comma-separated. Example: L02.2, L03.3.' },
    { key: 'management', description: 'Concise post-procedure plan in brief sentences.' },
  ]),
  mo('gastroscopy', 'Gastroscopy', [
    { key: 'patient_name', description: "Capture the patient's full name exactly as dictated, then re-format as 'Surname, Firstname' (do NOT add titles)." },
    { key: 'dob', description: "Patient's date of birth in DD-MM-YYYY format. Example: 29-08-1963." },
    { key: 'medical_aid', description: 'Exact name of the medical-aid scheme. Example: BANKMED.' },
    { key: 'id', description: '13-digit South-African ID number without spaces.' },
    { key: 'medical_aid_no', description: 'Exact medical-aid membership number as dictated.' },
    { key: 'date_endoscopy', description: 'Calendar date of the procedure in DD/MM/YYYY format.' },
    { key: 'start_time', description: 'Scope-in time in 24-hour HH:MM format.' },
    { key: 'end_time', description: 'Scope-out time in 24-hour HH:MM format.' },
    { key: 'endoscopist', description: 'Initials and surname of the endoscopist.', default: 'Patel MQ' },
    { key: 'anaesthetist', description: 'Initials and surname of the anaesthetist or procedural sedationist.' },
    { key: 'endoscopy_type', description: 'Type of endoscopy exactly as dictated.' },
    { key: 'procedure_codes', description: 'Comma-separated RPL procedure codes without explanations.' },
    { key: 'indication', description: 'Concise reason for the procedure in one sentence.' },
    { key: 'oesophagus', description: 'Exact findings for oesophagus section as dictated.' },
    { key: 'ogj', description: 'Findings for oesophageo-gastric junction exactly as dictated.' },
    { key: 'stomach', description: 'Stomach findings exactly as dictated.' },
    { key: 'duodenum', description: 'Duodenum findings exactly as dictated.' },
    { key: 'biopsies', description: 'Samples sent for pathology or microbiology. If none, type Not done.' },
    { key: 'diagnosis', description: 'Primary and secondary endoscopic diagnoses without codes; Title Case; semicolon-separated.' },
    { key: 'icds', description: 'Most relevant ICD-10 codes only, comma-separated.' },
    { key: 'management', description: 'Concise post-procedure plan in brief sentences.' },
  ]),
  mo('inpatient_fu', 'Inpatient Follow Up', [
    { key: 'patient_name', description: "Patient's full name formatted as 'Surname, Name'. Example: 'Smith, John'." },
    { key: 'dob', description: "Date of birth in DD-MM-YYYY format. Example: '15-07-1985'." },
    { key: 'medical_aid', description: "Medical aid provider name. Example: 'Momentum', 'Discovery'." },
    { key: 'id', description: 'South African ID number (13 digits).' },
    { key: 'medical_aid_no', description: 'Medical aid membership number as provided by the fund.' },
    { key: 'contact', description: 'Primary patient contact telephone number in local format.' },
    { key: 'fu_date', description: "Date of this follow up in DD-MM-YYYY format. Example: '12-08-2023'." },
    { key: 'admission_urgency', description: "Admission urgency: 'Emergency', 'Elective', or 'Urgent'." },
    { key: 'admission_ward_number', description: "Ward and bed/location string. Example: 'A7 Bed 5'." },
    { key: 'indication', description: 'Concise clinical indication for admission (no Python list format).' },
    { key: 'presenting_complaint', description: 'Verbatim presenting complaint in full sentences, mirroring clinician phrasing.' },
    { key: 'today', description: "Patient's complaints today (follow-up interval), as bullet points or brief sentences." },
    { key: 'vitals', description: 'Vital signs with correct SI units (all on the same line).' },
    { key: 'examination', description: 'Focused examination findings in concise clinical prose.' },
    { key: 'drain_output', description: 'All drain outputs since last review with device name/site, character, and volume in mL.' },
    { key: 'stoma_output', description: 'Stoma output details with type and volume in mL.' },
    { key: 'management_recommendations', description: 'Clear plan items, each on its own line (meds, fluids, imaging, consults, diet, mobility, follow-up).' },
    { key: 'additions_to_assessment', description: 'Any new problems/updates to the assessment since prior note.' },
  ]),
  mo('operation', 'Operation Report', [
    { key: 'patient_name', description: "Patient's full name as 'Surname, Firstname' (no titles)." },
    { key: 'dob', description: "Date of birth in DD-MM-YYYY format. Example: 20-06-1976." },
    { key: 'medical_aid', description: "Exact name of the patient's medical aid fund." },
    { key: 'id', description: 'South African 13-digit ID number with no spaces.' },
    { key: 'medical_aid_no', description: "Patient's medical-aid membership number exactly as dictated." },
    { key: 'contact', description: "Patient's primary contact number exactly as dictated." },
    { key: 'op_date', description: 'Calendar date of the operation in DD/MM/YYYY format.' },
    { key: 'start_time', description: 'Cut-time (knife-to-skin) in 24-hour HH:MM format.' },
    { key: 'end_time', description: 'Time of final dressing or closure in 24-hour HH:MM format.' },
    { key: 'surgeon', description: "Operating surgeon's initials and surname exactly as dictated." },
    { key: 'anaesthetist', description: "Anaesthetist's initials and surname." },
    { key: 'first_assistant', description: 'Name(s) of the first assistant(s). If none, write None.', default: 'None' },
    { key: 'second_assistant', description: 'Name of the second assistant. Leave blank if not applicable.', default: 'None' },
    { key: 'urgency_booking', description: 'Booking category (e.g., Emergency, Elective, Scheduled-Emergency).' },
    { key: 'operation_title', description: 'Concise operation name as dictated (sentence case, no codes).' },
    { key: 'procedure_codes', description: 'Comma-separated RPL procedure codes without explanations.' },
    { key: 'weight_height', description: "Patient's weight (kg) and height (m) in brackets as dictated." },
    { key: 'indication', description: 'Brief indication for the surgery in one sentence.' },
    { key: 'operative_findings', description: 'Intra-operative findings exactly as the surgeon dictates (no Python list format).' },
    { key: 'operation_note', description: 'Step-by-step operative narrative in past tense, each step on a new line.' },
    { key: 'biopsies', description: 'Samples sent for pathology/microbiology. If none, write None.' },
    { key: 'diagnosis', description: 'Post-operative diagnoses with plain-language descriptions; semicolon-separated.' },
    { key: 'icds', description: 'Most relevant ICD-10 codes only, comma-separated.' },
    { key: 'management', description: 'Concise post-operative management plan in brief sentences.' },
  ]),
  mo('outpt_consult', 'Outpatient Consult', [
    { key: 'patient_name', description: "Patient's surname, followed by first name. Format: 'Surname, Name'." },
    { key: 'dob', description: "Patient's date of birth in DD-MM-YYYY format." },
    { key: 'medical_aid', description: 'Medical aid provider name.' },
    { key: 'id', description: 'South African ID number (13 digits, no spaces).' },
    { key: 'medical_aid_no', description: 'Medical aid membership number.' },
    { key: 'contact', description: 'Primary patient contact number in local format.' },
    { key: 'consultation_date', description: 'Date of consultation in DD/MM/YYYY format.' },
    { key: 'admission_urgency', description: "Urgency: 'Emergency', 'Urgent', or 'Elective'." },
    { key: 'admission_ward_number', description: 'Ward and bed/location details as short free text.' },
    { key: 'indication', description: 'Brief indication(s) for admission as bullet points with ICD-10 codes where applicable.' },
    { key: 'presenting_complaint', description: 'Presenting complaint / HPC in full sentences.' },
    { key: 'pmh', description: 'Past medical history only; bullet points.' },
    { key: 'social_hx', description: 'Social history.' },
    { key: 'vitals', description: 'Vital signs with SI units on the same line.' },
    { key: 'examination', description: 'Focused examination findings as concise lines/bullets.' },
    { key: 'diagnosis', description: 'Working diagnosis as numbered list with ICD-10 codes in brackets.' },
    { key: 'management_recommendations', description: 'Management plan as bullet points.' },
  ]),
  mo('script', 'Script', [
    { key: 'icds', description: 'Most relevant ICD-10 codes for the patient conditions; one per line or newline-separated.' },
    { key: 'dob', description: "Patient DOB in dd-mm-yyyy format. Leave blank if not mentioned." },
    { key: 'patient_name', description: "Patient name as referred to in the transcript." },
    { key: 'medical_aid', description: 'Medical aid name and number if mentioned.' },
    { key: 'current_date', description: "Date of prescription in DD-MM-YYYY format.", from_profile: true },
    { key: 'prescription', description: 'Each prescribed medication on a new line numbered (1., 2., …) with name, dosage, and frequency.' },
  ]),
  mo('sick_note', 'Sick Note', [
    { key: 'patient_name', description: 'Full name and title of the patient (Mr./Mrs./Ms.) exactly as dictated.' },
    { key: 'date_of_exam', description: 'Date of examination in DD-MM-YYYY format.' },
    { key: 'diagnoses', description: "Patient's diagnoses exactly as dictated; bullet points." },
    { key: 'sick_start', description: 'Sick leave start date in DD/MM/YYYY format.' },
    { key: 'sick_end', description: 'Sick leave end date in DD/MM/YYYY format.' },
    { key: 'until', description: 'Date until amended duties, in DD/MM/YYYY format. Do not repeat sick leave dates.' },
    { key: 'follow_up', description: 'Follow-up date in DD/MM/YYYY format.' },
    { key: 'current_date', description: "Today's date in DD/MM/YYYY format.", from_profile: true },
  ]),
  mo('ward_dictation', 'Ward Dictation', [
    {
      key: 'dictation',
      description:
        'Structured daily surgical ward round note: for each patient (after "new patient"), use blocks for Surname/Name, Ward & Bed, DOB, ID, Primary Surgeon, Diagnosis (with ICD-10), Operation, Medical Aid, Current Condition, and Management Plan. Transcribe dictation word-for-word in this format.',
    },
  ]),
];
