import type { ClinicalTemplateDefinition } from './types';
import { MO_HALO_USER_ID, docPathForHaloUser } from './constants';

function mo(
  id: string,
  name: string,
  fields: ClinicalTemplateDefinition['fields'],
  description = ''
): ClinicalTemplateDefinition {
  return {
    template_id: id,
    name,
    description,
    doc_path: docPathForHaloUser(MO_HALO_USER_ID, id),
    fields,
  };
}

const COMMON_PATIENT_NAME_SPELLCHECK = [
  'Ayesha', 'Badenhorst', 'Barnard', 'Bester', 'Bezuidenhout', 'Botha', 'Bosch', 'Brown',
  'Burger', 'Coetzee', 'Coetzer', 'Cornelissen', 'de Beer', 'de Bruyn', 'de Jager', 'de Klerk',
  'de Lange', 'de Villiers', 'de Wet', 'du Plessis', 'du Preez', 'du Toit', 'Elsabe', 'Emily',
  'Erasmus', 'Esterhuizen', 'Evans', 'Ferreira', 'Fourie', 'Geldenhuys', 'Govender', 'Green',
  'Grobbelaar', 'Grobler', 'Groenewald', 'Heyns', 'Hofmeyr', 'Jacobs', 'Janse van Rensburg',
  'Jansen', 'Jean-Pierre', 'Joubert', 'Karla', 'Kotze', 'Kriek', 'Kruger', 'Kritzinger',
  'Labuschagne', 'Lategan', 'le Roux', 'Lewis', 'Lombard', 'Lottering', 'Lucia', 'Malan',
  'Malherbe', 'Marais', 'Michael', 'Mokoena', 'Mouton', 'Meyer', 'Myburgh', 'Naidoo', 'Naudé',
  'Neethling', 'Nel', 'Nell', 'Nikhil', 'Nieuwoudt', 'Olivier', 'Oosthuizen', 'Patel', 'Pienaar',
  'Pillay', 'Pretorius', 'Prinsloo', 'Rademeyer', 'Reddy', 'Reon', 'Roux', 'Scholtz',
  'Serfontein', 'Singh', 'Sipho', 'Smit', 'Snyman', 'Spero', 'Spies', 'Steyn', 'Thabo',
  'Thandi', 'Turner', 'van den Berg', 'van den Heever', 'van der Linde', 'van der Merwe',
  'van der Westhuizen', 'van der Walt', 'van Dyk', 'van Heerden', 'van Niekerk', 'van Rooyen',
  'van Tonder', 'van Wyk', 'van Zyl', 'Venter', 'Vermeulen', 'Vissagie', 'Visser', 'Vivier',
  'Vlok', 'Vrey', 'Wessels',
];

const COMMON_PATIENT_NAME_SPELLCHECK_WITH_NORTJE = [...COMMON_PATIENT_NAME_SPELLCHECK, 'Nortje'];

export const MO_CLINICAL_TEMPLATE_DEFINITIONS: ClinicalTemplateDefinition[] = [
  mo('admission', 'Admission', [
    {
      default: '',
      description:
        "Patient's surname, followed by first name, exactly as it should appear on clinical documents. Format: 'Surname, Name'. Example: 'van Rooy, Kaylen'.",
      key: 'patient_name',
      spell_check: COMMON_PATIENT_NAME_SPELLCHECK,
    },
    { default: '', description: "Patient's date of birth in DD-MM-YYYY format. Example: '02-02-2007'.", key: 'dob' },
    {
      default: '',
      description: "Medical aid provider name. Example: 'LA Health'.",
      key: 'medical_aid',
      spell_check: ['Discovery', 'Momentum', 'GEMS', 'Motohealth', 'Bonitas', 'BP Southern Africa Medical Aid', 'Medihelp', 'Bestmed', 'Bankmed', 'Medshield', 'Fedhealth', 'Keyhealth', 'Profmed', 'LA Health'],
    },
    { default: '', description: "South African ID number (13 digits, no spaces). Example: '0702020202082'.", key: 'id' },
    { default: '', description: "Medical aid membership number as provided by the patient/insurer. Example: '915566050'.", key: 'medical_aid_no' },
    { default: '', description: "Primary patient contact number in local format. Example: '021 555 0123' or '082 123 4567'.", key: 'contact' },
    { default: '', description: "Date of admission in DD/MM/YYYY format. Example: '30/05/2025'.", key: 'admission_date' },
    {
      default: '',
      description: "Urgency of admission. Use one word such as 'Emergency', 'Urgent', or 'Elective'. Example: 'Emergency'.",
      key: 'admission_urgency',
      spell_check: ['Emergency', 'Urgent', 'Elective'],
    },
    { default: '', description: "Ward and bed/location details as short free text. Example: 'S10' or 'A7 Bed 5'.", key: 'admission_ward_number' },
    {
      default: '',
      description:
        'Brief indication(s) for admission as bullet points (do not use Python list format). Include ICD-10 codes in brackets where applicable. Example:\n- L03.3 Cellulitis of breast\n- N61 Inflammatory disorder of the breast',
      key: 'indication',
      spell_check: ['cellulitis', 'abscess', 'perforation', 'haematemesis', 'melaena', 'appendicitis', 'diverticulitis', 'peritonitis', 'cholecystitis', 'iliac fossa', 'ischaemia'],
    },
    {
      default: '',
      description:
        "Presenting complaint/history of presenting complaint written in full sentences. Use bullet points only if the doctor uses them in dictation. Keep the doctor's order/wording and standard clinical abbreviations. Example:\n'Left breast swelling and pain of 5 days’ duration with fever and purulent nipple discharge.'",
      key: 'presenting_complaint',
      spell_check: ['dysphagia', 'haematemesis', 'melaena', 'haematochezia', 'dyspnoea', 'perianal', 'iliac fossa', 'inguinal', 'perforation', 'fistula', 'stricture'],
    },
    {
      default: '',
      description:
        'Past medical history only (exclude current complaint, investigations, and treatment). Use bullet points (do not use Python list format). Example:\n- Known eczema involving bilateral breasts\n- No chronic illnesses reported',
      key: 'pmh',
      spell_check: ['eczema', 'hypertension', 'diabetes', 'hypercholesterolaemia', 'asthma', 'psoriasis', 'nexiam', 'iliac fossa', 'tuberculosis'],
    },
    { default: '', description: 'Social history (occupation, schooling, breastfeeding status where relevant, habits). Example:\n- School student (matric)\n- Not breastfeeding', key: 'social_hx' },
    {
      default: '',
      description:
        'Vital signs with correct SI units/medical notation (mmHg, °C, /min, %, room air). Put them all on the same line. Example:\nTemp: 38.0 °C  HR: 108 /min  RR: 12 /min  BP: 118/76 mmHg  SpO₂: 99% on room air',
      key: 'vitals',
    },
    {
      default: '',
      description:
        'Focused examination findings as concise lines/bullets (do not use Python list format). Example:\n- Left breast: tender subareolar fluctuant collection with overlying erythema\n- Palpable left axillary lymph nodes\n- No generalised lymphadenopathy',
      key: 'examination',
      spell_check: ['erythema', 'fluctuant', 'crepitus', 'necrosis', 'lymphadenopathy', 'hepatomegaly', 'Pfannenstiel', 'splenomegaly', 'peritonism', 'iliac fossa', 'guarding', 'rebound tenderness'],
    },
    {
      default: '',
      description:
        'Primary working diagnosis (or differentials) as a numbered list with ICD-10 codes in brackets. Do not use Python list format. Example:\n1. Breast cellulitis with abscess and tissue necrosis (N61, L02.9)\n2. Sepsis — breast source (A41.9) if applicable',
      key: 'diagnosis',
      spell_check: ['carcinoma', 'adenocarcinoma', 'sarcoma', 'diverticulitis', 'appendicitis', 'peritonitis', 'cholecystitis', 'pancreatitis', 'iliac fossa', 'haemoperitoneum', 'ischaemia'],
    },
    {
      default: '',
      description:
        'Management plan as bullet points (do not use Python list format). Include procedures, imaging, antibiotics/fluids, and consent status. Use SI units/standard abbreviations. Example:\n- Intravenous antibiotics\n- Breast ultrasound\n- Incision & drainage and debridement of left breast\n- Consent obtained from patient/guardian',
      key: 'management_recommendations',
      spell_check: ['laparotomy', 'laparoscopy', 'colectomy', 'Pfannenstiel', 'cholecystectomy', 'gastrectomy', 'anastomosis', 'nexiam', 'resection', 'iliac fossa', 'ostomy', 'debridement', 'Duforzig', 'Glicazide', 'incision and drainage'],
    },
  ]),
  mo('colonoscopy', 'Colonoscopy', [
    {
      default: '',
      description: "Be a professional medical typist. Capture the patient's full name exactly as dictated, then re-format as 'Surname, Firstname' (do NOT add titles). Example: Klein, Rosaline.",
      key: 'patient_name',
      spell_check: COMMON_PATIENT_NAME_SPELLCHECK_WITH_NORTJE,
    },
    { default: '', description: 'Patient’s date of birth in DD-MM-YYYY format. Example: 29-08-1963.', key: 'dob' },
    { default: '', description: 'Exact name of the medical-aid scheme. Example: BANKMED.', key: 'medical_aid', spell_check: ['Discovery', 'Momentum', 'Motohealth', 'Bonitas', 'Medihelp', 'Bestmed', 'Bankmed', 'Medshield', 'Fedhealth', 'Keyhealth', 'Profmed', 'LA Health'] },
    { default: '', description: '13-digit South-African ID number without spaces. Example: 6308290238089.', key: 'id' },
    { default: '', description: 'Exact medical-aid membership number as dictated. Example: 512509260.', key: 'medical_aid_no' },
    { default: '', description: 'Calendar date of the procedure in DD/MM/YYYY format. Example: 17/04/2025.', key: 'date_endoscopy' },
    { default: '', description: 'Scope-in time in 24-hour HH:MM format. Example: 19:31.', key: 'start_time' },
    { default: '', description: 'Scope-out time in 24-hour HH:MM format. Example: 20:28.', key: 'end_time' },
    { default: 'Patel MQ', description: 'Initials and surname of the endoscopist exactly as dictated. Example: Patel MQ.', key: 'endoscopist', spell_check: ['Patel', 'Moodley', 'Steyn', 'Fourie', 'Smith', 'Bester', 'Khoza', 'Petersen', 'Van Wyk', 'Khumalo'] },
    { default: '', description: 'Initials and surname of the anaesthetist or procedural sedationist. Example: Odendaal P.', key: 'anaesthetist', spell_check: ['Odendaal', 'Steytler', 'Govender', 'Singh', 'Van Zyl', 'Marais', 'Maharaj', 'Nordien', 'Maseko', 'Jonker'] },
    { default: '', description: 'Type of endoscopy exactly as dictated (e.g., Colonoscopy, Gastroscopy, Flexible Sigmoidoscopy, ERCP).', key: 'endoscopy_type' },
    { default: '', description: 'Be an expert RPL code suggestor and populate the most relevant RPL codes based on the details included in this operation. These are to be submitted for billing so must be accurate and populated from your own knowledge. Foramt as a comma-separated list of procedure codes (RPL) **without** explanations. Example: `0257, 0304, 0011, 0018`.', key: 'procedure_codes' },
    { default: '', description: 'Concise reason for the procedure in one sentence. Example: GI bleed with melaena.', key: 'indication', spell_check: ['haematemesis', 'malaena', 'haematochezia', 'anaemia', 'polyp surveillance', 'abdominal pain', 'weight loss', 'change in bowel habit', 'diverticulitis', 'Crohn’s', 'ulcerative colitis'] },
    { default: '', description: "Report the Boston Bowel Prep Score (BBPS) out of 9, giving 3 separate scores (0–3) for the left, transverse, and right colon, and then the sum of all 3 in that order. Format as 'Left; Transverse; Right; Sum'. Example: L3; T3; R3; Sum: 9 or L2; T3; R1; Sum: 6.", key: 'boston_score' },
    { default: '', description: 'Exact findings for anus and rectum section as dictated. Example: Normal.', key: 'anus_rectum', spell_check: ['haemorrhoids', 'anal fissure', 'proctitis', 'ulcerations', 'polyps', 'diverticulosis', 'erythema', 'angiodysplasia'] },
    { default: '', description: 'Findings for sigmoid and left colon exactly as dictated. Example: Diverticulosis, no inflammation.', key: 'sigmoid_left_colon', spell_check: ['diverticulosis', 'diverticulitis', 'stricture', 'erythema', 'ulceration', 'polyp', 'adenoma', 'colitis', 'ischaemia'] },
    { default: '', description: 'Transverse-colon findings exactly as dictated. Example: Normal mucosa.', key: 'transverse_colon', spell_check: ['tumour', 'polyp', 'colitis', 'melanosis', 'angiodysplasia'] },
    { default: '', description: 'Ascending colon and caecum findings exactly as dictated. Example: Normal mucosa.', key: 'right_colon', spell_check: ['caecum', 'ileocaecal', 'appendiceal orifice', 'angiodysplasia', 'ulcer', 'polyp', 'adenocarcinoma', 'AVM'] },
    { default: '', description: 'Ileal findings including whether intubated. Example: Intubated, normal mucosa, no ileitis.', key: 'ileum', spell_check: ['ileitis', 'Crohn’s', 'ulceration', 'nodularity', 'erosion', 'villous atrophy', 'aphthous'] },
    { default: '', description: 'Samples sent for pathology or microbiology. If none, type Not done. Example: Random biopsies from transverse colon for microscopic colitis.', key: 'biopsies', spell_check: ['histology', 'cytology', 'MCS', 'biopsy', 'culture', 'sensitivity', 'immunohistochemistry'] },
    { default: '', description: 'Primary and secondary endoscopic diagnoses without codes; use Title Case and separate multiple items with semicolons. Example: Colonic diverticulosis.', key: 'diagnosis', spell_check: ['diverticulosis', 'diverticulitis', 'polyp', 'adenoma', 'angiodysplasia', 'haemorrhoids', 'ulcerative colitis', 'Crohn’s disease', 'microscopic colitis', 'ischaemic colitis'] },
    { default: '', description: 'Be a professional ICD10 code suggester and list the most relevant ICD-10 codes **only**, separated by commas. If code not dictated, populate from your knowledge. Example: `L02.2, L03.3`.', key: 'icds' },
    { default: '', description: 'Concise post-procedure plan in brief sentences. Example: Referral to medical gastroenterologist; consider capsule endoscopy.', key: 'management', spell_check: ['omeprazole', 'ciprofloxacin', 'metronidazole', 'rifaximin', 'follow-up', 'capsule endoscopy', 'CT colonography', 'surveillance colonoscopy', 'dietary advice'] },
  ]),
  mo('gastroscopy', 'Gastroscopy', [
    {
      default: '',
      description: "Be a professional medical typist. Capture the patient's full name exactly as dictated, then re-format as 'Surname, Firstname' (do NOT add titles). Example: Klein, Rosaline.",
      key: 'patient_name',
      spell_check: COMMON_PATIENT_NAME_SPELLCHECK_WITH_NORTJE,
    },
    { default: '', description: 'Patient’s date of birth in DD-MM-YYYY format. Example: 29-08-1963.', key: 'dob' },
    { default: '', description: 'Exact name of the medical-aid scheme. Example: BANKMED.', key: 'medical_aid', spell_check: ['Discovery', 'Momentum', 'Motohealth', 'Bonitas', 'Medihelp', 'Bestmed', 'Bankmed', 'Medshield', 'Fedhealth', 'Keyhealth', 'Profmed', 'LA Health'] },
    { default: '', description: '13-digit South-African ID number without spaces. Example: 6308290238089.', key: 'id' },
    { default: '', description: 'Exact medical-aid membership number as dictated. Example: 512509260.', key: 'medical_aid_no' },
    { default: '', description: 'Calendar date of the procedure in DD/MM/YYYY format. Example: 17/04/2025.', key: 'date_endoscopy' },
    { default: '', description: 'Scope-in time in 24-hour HH:MM format. Example: 19:31.', key: 'start_time' },
    { default: '', description: 'Scope-out time in 24-hour HH:MM format. Example: 20:28.', key: 'end_time' },
    { default: 'Patel MQ', description: 'Initials and surname of the endoscopist exactly as dictated. Example: Patel MQ.', key: 'endoscopist', spell_check: ['Patel', 'Moodley', 'Steyn', 'Fourie', 'Smith', 'Bester', 'Khoza', 'Petersen', 'Van Wyk', 'Khumalo'] },
    { default: '', description: 'Initials and surname of the anaesthetist or procedural sedationist. Example: Odendaal P.', key: 'anaesthetist', spell_check: ['Odendaal', 'Steytler', 'Govender', 'Singh', 'Van Zyl', 'Marais', 'Maharaj', 'Nordien', 'Maseko', 'Jonker'] },
    { default: '', description: 'Type of endoscopy exactly as dictated (e.g., Colonoscopy, Gastroscopy, Flexible Sigmoidoscopy, ERCP).', key: 'endoscopy_type' },
    { default: '', description: 'Be an expert RPL code suggestor and populate the most relevant RPL codes based on the details included in this operation. These are to be submitted for billing so must be accurate and populated from your own knowledge. Foramt as a comma-separated list of procedure codes (RPL) **without** explanations. Example: `0257, 0304, 0011, 0018`.', key: 'procedure_codes' },
    { default: '', description: 'Concise reason for the procedure in one sentence. Example: GI bleed with melaena.', key: 'indication', spell_check: ['haematemesis', 'melaena', 'haematochezia', 'anaemia', 'polyp surveillance', 'abdominal pain', 'weight loss', 'change in bowel habit', 'diverticulitis', 'Crohn’s', 'ulcerative colitis'] },
    { default: '', description: 'Exact findings for oesophagus section as dictated. Example: Severe oesophagitis.', key: 'oesophagus', spell_check: ['haemorrhoids', 'anal fissure', 'proctitis', 'ulcerations', 'polyps', 'diverticulosis', 'erythema', 'angiodysplasia'] },
    { default: '', description: 'Findings for oesophageo-gastric junction exactly as dictated. Example: At 35cm, no hiatus hernia.', key: 'ogj', spell_check: ['diverticulosis', 'diverticulitis', 'stricture', 'erythema', 'ulceration', 'polyp', 'adenoma', 'colitis', 'ischaemia'] },
    { default: '', description: 'Stomach findings exactly as dictated. Example: Some mild gastritis at insura.', key: 'stomach', spell_check: ['tumour', 'polyp', 'fundoplication', 'colitis', 'melanosis', 'angiodysplasia'] },
    { default: '', description: 'Duodenum findings exactly as dictated. Example: Normal duodenum, scope passed into D2 of the duodenum.', key: 'duodenum', spell_check: ['caecum', 'ileocaecal', 'appendiceal orifice', 'angiodysplasia', 'ulcer', 'fundoplication', 'polyp', 'adenocarcinoma', 'AVM'] },
    { default: '', description: 'Samples sent for pathology or microbiology. If none, type Not done. Example: Random biopsies from transverse colon for microscopic colitis.', key: 'biopsies', spell_check: ['histology', 'cytology', 'fundoplication', 'MCS', 'biopsy', 'culture', 'sensitivity', 'immunohistochemistry'] },
    { default: '', description: 'Primary and secondary endoscopic diagnoses without codes; use Title Case and separate multiple items with semicolons. Example: Colonic diverticulosis.', key: 'diagnosis', spell_check: ['diverticulosis', 'diverticulitis', 'polyp', 'adenoma', 'angiodysplasia', 'fundoplication', 'haemorrhoids', 'ulcerative colitis', 'Crohn’s disease', 'microscopic colitis', 'ischaemic colitis'] },
    { default: '', description: 'Be a professional ICD10 code suggester and list the most relevant ICD-10 codes **only**, separated by commas. If code not dictated, populate from your knowledge. Example: `L02.2, L03.3`.', key: 'icds' },
    { default: '', description: 'Concise post-procedure plan in brief sentences. Example: Referral to medical gastroenterologist; consider capsule endoscopy.', key: 'management', spell_check: ['omeprazole', 'ciprofloxacin', 'metronidazole', 'rifaximin', 'follow-up', 'capsule endoscopy', 'CT colonography', 'surveillance colonoscopy', 'fundoplication', 'dietary advice'] },
  ]),
  mo('inpatient_fu', 'Inpatient Follow Up', [
    { default: '', description: "Patient’s full name formatted as 'Surname, Name'. Example: 'Smith, John'.", key: 'patient_name', spell_check: COMMON_PATIENT_NAME_SPELLCHECK_WITH_NORTJE },
    { default: '', description: "Date of birth in DD-MM-YYYY format. Example: '15-07-1985'.", key: 'dob' },
    { default: '', description: "Medical aid provider name. Example: 'Momentum', 'Discovery'.", key: 'medical_aid', spell_check: ['Discovery', 'Momentum', 'Motohealth', 'Bonitas', 'Medihelp', 'Bestmed', 'Bankmed', 'Medshield', 'Fedhealth', 'Keyhealth', 'Profmed', 'LA Health'] },
    { default: '', description: "South African ID number (13 digits). Example: '8507151234087'.", key: 'id' },
    { default: '', description: "Medical aid membership number as provided by the fund. Example: '12345678'.", key: 'medical_aid_no' },
    { default: '', description: "Primary patient contact telephone number in local format. Example: '012 345 6789' or '+27 12 345 6789'.", key: 'contact' },
    { default: '', description: "Date of this follow up in DD-MM-YYYY format. Example: '12-08-2023'.", key: 'fu_date' },
    { default: '', description: "Admission urgency exactly as documented. Common values: 'Emergency', 'Elective', 'Urgent'. Example: 'Emergency'.", key: 'admission_urgency', spell_check: ['Emergency', 'Elective', 'Urgent'] },
    { default: '', description: "Ward and bed/location string as written by the clinician. Example: 'A7 Bed 5'.", key: 'admission_ward_number' },
    { default: '', description: 'Concise clinical indication for admission in one or more short lines (no Python list format). Example:\n- Chest pain on breathing', key: 'indication', spell_check: ['dyspnoea', 'pleuritic', 'haematemesis', 'syncope', 'sepsis', 'appendicitis', 'cholecystitis', 'pancreatitis', 'diverticulitis', 'melaena'] },
    { default: '', description: "Verbatim presenting complaint in full sentences, mirroring clinician phrasing. Keep SI units and clinical terms correct. Example: 'Chest pain on breathing.'", key: 'presenting_complaint', spell_check: ['dyspnoea', 'orthopnoea', 'pleurisy', 'palpitations', 'haemoptysis', 'stridor', 'claudication', 'haematochezia', 'odynophagia', 'syncope'] },
    { default: '', description: 'Patient’s complaints today (follow-up interval), as bullet points or brief sentences; do not use Python list format. Example:\n- Persistent right iliac fossa pain\n- Nausea improved\n- Passing flatus', key: 'today', spell_check: ['nausea', 'vomiting', 'flatus', 'diarrhoea', 'constipation', 'haematuria', 'fatigue', 'dysuria'] },
    { default: '', description: 'Vital signs with correct SI units and standard notation (all vital signs must be on the same line, not Python list). Example:\nTemp 36.8 °C\nHR 72 /min\nRR 14 /min\nBP 118/76 mmHg\nSpO₂ 99% RA', key: 'vitals' },
    { default: '', description: 'Focused examination findings in concise clinical prose (new lines as needed). Exclude investigations; keep SI units standard. Example: \'Abdomen soft, non-tender. No guarding or rebound. Erythematous plaques on forearms with silvery scales.\'', key: 'examination', spell_check: ['erythematous', 'lymphadenopathy', 'hepatosplenomegaly', 'crepitus', 'oedema', 'ascites', 'peritonism', 'guarding', 'rebound', 'necrosis'] },
    { default: '', description: 'All drain outputs since last review with device name/site, character, and volume in mL (new line per drain). Do not include stomas. Example:\nICU drain #1: 120 mL serosanguinous/24 h\nPelvic drain: 30 mL serous/24 h', key: 'drain_output', spell_check: ['serous', 'serosanguinous', 'purulent', 'haemorrhagic', 'bilious', 'chylous'] },
    { default: '', description: 'Stoma output details with type and volume in mL (new line per entry). Example:\nIleostomy: 550 mL thin bilious/24 h\nColostomy: 300 mL formed/24 h', key: 'stoma_output', spell_check: ['ileostomy', 'colostomy', 'urostomy', 'jejunostomy', 'mucous fistula', 'bilious', 'faeculent'] },
    { default: '', description: 'Clear plan items, each on its own line (no Python list format). Include meds (dose/route/frequency), fluids, imaging, consults, diet, mobility, and follow-up. Example:\n- IV fluids: Ringer’s lactate 1,000 mL over 8 h\n- Start ceftriaxone 1 g IV daily\n- NPO from midnight for CT abdomen in AM\n- DVT prophylaxis: enoxaparin 40 mg SC nocte', key: 'management_recommendations', spell_check: ['ceftriaxone', 'piperacillin–tazobactam', 'enoxaparin', 'omeprazole', 'paracetamol', 'ondansetron', 'meropenem', 'metronidazole', 'fluconazole'] },
    { default: '', description: 'Any new problems/updates to the assessment since prior note, in brief sentences or bullet points (no Python list format). Example:\n- Increasing drain output—monitor Hb and trends\n- Pain improved on current regimen', key: 'additions_to_assessment', spell_check: ['tachycardia', 'hypotension', 'oliguria', 'anaemia', 'pyrexia', 'ileus'] },
  ]),
  mo('operation', 'Operation Report', [
    { default: '', description: "Be a professional medical typist. Capture the patient’s full name exactly as the surgeon dictates, then format as **'Surname, Firstname'** (do **NOT** add titles such as Mr/Mrs/Dr). Example: `Klein, Rosaline`.", key: 'patient_name', spell_check: COMMON_PATIENT_NAME_SPELLCHECK_WITH_NORTJE },
    { default: '', description: 'The patient’s date of birth in DD-MM-YYYY format. Example: `20-06-1976`.', key: 'dob' },
    { default: '', description: 'Exact name of the patient’s medical aid fund. Example: `REMEDI`.', key: 'medical_aid', spell_check: ['Discovery', 'Momentum', 'Motohealth', 'Bonitas', 'Medihelp', 'Bestmed', 'Bankmed', 'Medshield', 'Fedhealth', 'Remedei', 'Keyhealth', 'Profmed', 'LA Health'] },
    { default: '', description: 'South African 13-digit ID number with no spaces. Example: `7606200174081`.', key: 'id' },
    { default: '', description: 'Patient’s medical-aid membership number exactly as dictated. Example: `372869111`.', key: 'medical_aid_no' },
    { default: '', description: 'Patient’s primary contact number exactly as dictated, in local or international format. Example: `0824441484`.', key: 'contact' },
    { default: '', description: 'The calendar date on which the operation took place in **DD/MM/YYYY** format. Example: `31/05/2025`.', key: 'op_date' },
    { default: '', description: 'Cut-time (knife-to-skin) in 24-hour **HH:MM** format. Example: `10:35`.', key: 'start_time' },
    { default: '', description: 'Time of final dressing or closure in 24-hour **HH:MM** format. Example: `10:55`.', key: 'end_time' },
    { default: '', description: 'Operating surgeon’s initials and surname exactly as dictated (e.g., `Patel MQ`).', key: 'surgeon', spell_check: ['Patel', 'Moodley', 'Steyn', 'Fourie', 'Smith', 'Bester', 'Khoza', 'Petersen', 'Van Wyk', 'Khumalo'] },
    { default: '', description: 'Anaesthetist’s initials and surname. Example: `Steytler F`.', key: 'anaesthetist', spell_check: ['Steytler', 'Govender', 'Swanepoel', 'Singh', 'Van Zyl', 'Maharaj', 'Jonker', 'Maseko', 'Nordien', 'Mkhize'] },
    { default: 'None', description: 'Name(s) of the first assistant(s). If none, write `None`.', key: 'first_assistant', spell_check: ['None'] },
    { default: 'None', description: 'Name of the second assistant. Leave blank if not applicable.', key: 'second_assistant' },
    { default: '', description: 'Booking category exactly as the surgeon states (e.g., `Emergency`, `Elective`, `Scheduled-Emergency`).', key: 'urgency_booking' },
    { default: '', description: 'Concise operation name as dictated (sentence case, no codes). Example: `Incision, Drainage & Debridement of Abscess on Back`.', key: 'operation_title', spell_check: ['Appendectomy', 'Cholecystectomy', 'Hernia Repair', 'Laparotomy', 'Mastectomy', 'Hemicolectomy', 'Debridement', 'Thoracotomy', 'Colectomy', 'Gastrectomy'] },
    { default: '', description: 'Be an expert RPL code suggestor and populate the most relevant RPL codes based on the details included in this operation. These are to be submitted for billing so must be accurate and populated from your own knowledge. Foramt as a comma-separated list of procedure codes (RPL) **without** explanations. Example: `0257, 0304, 0011, 0018`.', key: 'procedure_codes' },
    { default: '', description: 'Patient’s weight (kg) and height (m) in brackets as dictated. Example: `(wt 120 kg, ht 1.61 m)`.', key: 'weight_height' },
    { default: '', description: 'Brief indication for the surgery in one sentence. Example: `GI bleed with malaena.`', key: 'indication', spell_check: ['haematemesis', 'melaena', 'peritonitis', 'obstruction', 'symphysis pubis', 'perforation', 'sepsis', 'haematochezia', 'appendicitis', 'cholangitis', 'diverticulitis'] },
    { default: '', description: 'Free-text narrative or bullet-points of intra-operative findings **exactly** as the surgeon dictates. Avoid Python list format. Example:\n```\nLarge abscess at right abdominal wall with slough and necrotic tissue\n```', key: 'operative_findings', spell_check: ['haematoma', 'necrotic', 'serosa', 'omentum', 'mesentery', 'retroperitoneal', 'purulent', 'symphysis pubis', 'fistula', 'adhesions', 'ischaemic', 'anterior wall', 'Anterior wall', 'gallbladder mucosa', 'Mucosa', 'fulgurated', 'Fulgurated'] },
    { default: '', description: "Step-by-step operative narrative in past tense, each step on a new line (no Python lists). Preserve surgeon’s wording. Make as detailed as possible without adding any unmnetioned details. Example: 'General anaesthesia. Supine position. WHO checklist completed.\nSupra-umbilical port placed using open Hasson technique.\nPneumoperitoneum established to 12 mmHg.\nStandard 11 mm port and two 5 mm ports placed under direct vision.\nAdhesions noted at Calot’s triangle.\nGallbladder peritoneum opened medially and laterally.\nCritical View of Safety achieved.\nIntraoperative ultrasound performed demonstrating double duct at level of CBD with low insertion of cystic duct. Intrahepatic ducts, common hepatic duct and common bile duct patent with no acoustic shadowing.\nCystic duct partially opened and intraoperative cholangiogram performed, confirming low insertion of cystic duct onto CBD, patent intrahepatic ducts, common hepatic duct and common bile duct, no filling defects and free flow of contrast into the duodenum.\nCystic duct and cystic artery clipped with three gold Hem-o-lok clips and transected.\nGallbladder dissected from liver bed using hook diathermy. Good haemostasis achieved.\nGallbladder retrieved in an EndoCatch bag.\nPorts removed under direct vision. Fascial sheath closed with 1/0 nylon. Skin closed with 3/0 Monocryl.\n'", key: 'operation_note', spell_check: ['haemostasis', 'Kocherised', 'electrocautery', 'Vicryl', 'PDS', 'Monocryl', 'symphysis pubis', 'Betadine', 'laparoscopic', 'washout', 'haemolock', 'Hem-o-lok', 'Haem-o-lok', 'purple haemolock', 'Purple haemolock', 'GIA stapler', 'ileostomy', 'Hartmann’s', "Hartmann's", "Hartmann's Pouch", 'Hartmann’s Pouch', 'haemorrhage', 'Pathcare', 'closure', 'Supraumbilical', 'supraumbilical', 'Open Hasson technique', 'Open Hassan Technique', 'Open Hasson Technique', 'Hasson', 'Hassan', 'Hasson technique', 'Hassan technique', 'Anterior wall', 'anterior wall', 'Buitendag J', 'JDW', 'JDW Pathology', 'Histopathology', 'gallbladder', 'Gallbladder', 'mucosa', 'Mucosa', 'fulgurated', 'Fulgurated', 'thromboprophylaxis', 'Thromboprophylaxis', 'MCS', 'PathCare', 'Pathcare'] },
    { default: '', description: 'Samples sent for pathology/microbiology. If none, write `None`. Example: `Pus swab and tissue for MCS`.', key: 'biopsies', spell_check: ['histology', 'cytology', 'MCS', 'biopsy', 'culture', 'Pathcare', 'PathCare', 'sensitivity', 'Histopathology', 'JDW', 'JDW Pathology', 'gallbladder wall', 'Gallbladder wall', 'pus', 'Pus'] },
    { default: '', description: 'Primary and secondary post-operative diagnoses **with** plain-language descriptions (no codes). Separate multiple with semicolons. Do not include chronic pre-existing conditions here, only the acute diagnosis for which the patient has presented. Example: `Abscess of abdominal wall; Cellulitis of trunk`.', key: 'diagnosis', spell_check: ['cellulitis', 'abscess', 'symphysis pubis', 'fistula', 'hernia', 'peritonitis', 'appendicitis', 'diverticulitis', 'cholecystitis', 'pancreatitis', 'perforation', 'anterior wall', 'Anterior wall', 'gallbladder', 'Gallbladder'] },
    { default: '', description: 'Be a professional ICD10 code suggester and list the most relevant ICD-10 codes **only**, separated by commas. If code not dictated, populate from your knowledge. Example: `L02.2, L03.3`.', key: 'icds' },
    { default: '', description: 'Concise post-operative management plan using brief sentences (no Python lists). Example:\n```\nWound care, follow-up MCS results, antibiotics.\n```', key: 'management', spell_check: ['cefazolin', 'Sorbact', 'piperacillin–tazobactam', 'clindamycin', 'vancomycin', 'analgesia', 'physiotherapy', 'Pathcare', 'PathCare', 'dressing', 'culture', 'follow-up', 'analgesics', 'thromboprophylaxis', 'Thromboprophylaxis', 'MCS'] },
  ]),
  mo('outpt_consult', 'Outpatient Consult', [
    { default: '', description: "Patient’s surname, followed by first name, exactly as it should appear on clinical documents. Format: 'Surname, Name'. Example: 'van Rooy, Kaylen'.", key: 'patient_name', spell_check: COMMON_PATIENT_NAME_SPELLCHECK_WITH_NORTJE },
    { default: '', description: "Patient’s date of birth in DD-MM-YYYY format. Example: '02-02-2007'.", key: 'dob' },
    { default: '', description: "Medical aid provider name. Example: 'LA Health'.", key: 'medical_aid', spell_check: ['Discovery', 'Momentum', 'Motohealth', 'Bonitas', 'Medihelp', 'Bestmed', 'Bankmed', 'Medshield', 'Fedhealth', 'Remedei', 'Keyhealth', 'Profmed', 'LA Health'] },
    { default: '', description: "South African ID number (13 digits, no spaces). Example: '0702020202082'.", key: 'id' },
    { default: '', description: "Medical aid membership number as provided by the patient/insurer. Example: '915566050'.", key: 'medical_aid_no' },
    { default: '', description: "Primary patient contact number in local format. Example: '021 555 0123' or '082 123 4567'.", key: 'contact' },
    { default: '', description: "Date of consultation in DD/MM/YYYY format. Example: '30/05/2025'.", key: 'consultation_date' },
    { default: '', description: "Urgency of admission. Use one word such as 'Emergency', 'Urgent', or 'Elective'. Example: 'Emergency'.", key: 'admission_urgency', spell_check: ['Emergency', 'Urgent', 'Elective'] },
    { default: '', description: "Ward and bed/location details as short free text. Example: 'S10' or 'A7 Bed 5'.", key: 'admission_ward_number' },
    { default: '', description: 'Brief indication(s) for admission as bullet points (do not use Python list format). Include ICD-10 codes in brackets where applicable. Example:\n- L03.3 Cellulitis of breast\n- N61 Inflammatory disorder of the breast', key: 'indication', spell_check: ['cellulitis', 'abscess', 'haematemesis', 'melaena', 'appendicitis', 'diverticulitis', 'peritonitis', 'cholecystitis', 'pancreatitis', 'ischaemia'] },
    { default: '', description: "Presenting complaint/history of presenting complaint written in full sentences. Use bullet points only if the doctor uses them in dictation. Keep the doctor’s order/wording and standard clinical abbreviations. Example:\n'Left breast swelling and pain of 5 days’ duration with fever and purulent nipple discharge.'", key: 'presenting_complaint', spell_check: ['dysphagia', 'haematemesis', 'melaena', 'haematochezia', 'dyspnoea', 'odynophagia', 'stridor', 'fistula', 'stricture', 'syncope'] },
    { default: '', description: 'Past medical history only (exclude current complaint, investigations, and treatment). Use bullet points (do not use Python list format). Example:\n- Known eczema involving bilateral breasts\n- No chronic illnesses reported', key: 'pmh', spell_check: ['eczema', 'hypertension', 'diabetes', 'hypercholesterolaemia', 'asthma', 'psoriasis', 'tuberculosis'] },
    { default: '', description: 'Social history (occupation, schooling, breastfeeding status where relevant, habits). Example:\n- School student (matric)\n- Not breastfeeding', key: 'social_hx' },
    { default: '', description: 'Vital signs with correct SI units/medical notation (mmHg, °C, /min, %, room air). Put them all on the same line. Example:\nTemp: 38.0 °C  HR: 108 /min  RR: 12 /min  BP: 118/76 mmHg  SpO₂: 99% on room air', key: 'vitals' },
    { default: '', description: 'Focused examination findings as concise lines/bullets (do not use Python list format). Example:\n- Left breast: tender subareolar fluctuant collection with overlying erythema\n- Palpable left axillary lymph nodes\n- No generalised lymphadenopathy', key: 'examination', spell_check: ['erythema', 'fluctuant', 'crepitus', 'necrosis', 'lymphadenopathy', 'hepatomegaly', 'splenomegaly', 'ascites', 'peritonism', 'rebound tenderness'] },
    { default: '', description: 'Primary working diagnosis (or differentials) as a numbered list with ICD-10 codes in brackets. Do not use Python list format. Example:\n1. Breast cellulitis with abscess and tissue necrosis (N61, L02.9)\n2. Sepsis — breast source (A41.9) if applicable', key: 'diagnosis', spell_check: ['carcinoma', 'adenocarcinoma', 'sarcoma', 'diverticulitis', 'appendicitis', 'peritonitis', 'cholecystitis', 'pancreatitis', 'haemoperitoneum', 'ischaemia'] },
    { default: '', description: 'Management plan as bullet points (do not use Python list format). Include procedures, imaging, antibiotics/fluids, and consent status. Use SI units/standard abbreviations. Example:\n- Intravenous antibiotics\n- Breast ultrasound\n- Incision & drainage and debridement of left breast\n- Consent obtained from patient/guardian', key: 'management_recommendations', spell_check: ['laparotomy', 'laparoscopy', 'colectomy', 'cholecystectomy', 'gastrectomy', 'anastomosis', 'ostomy', 'debridement', 'incision and drainage', 'Roux-en-Y'] },
  ]),
  mo('script', 'Script', [
    { default: '', description: "Be a professional ICD10 code extractor and list the most relevant ICD-10 codes for the patient's conditions. If the ICD10 codes are not mentioned in the transcript, extract them from your own knowledge. Write each code on a new line. If multiple codes, separate them with newlines. Do not use Python list format. Example: 'I46.9\nI10'", key: 'icds', spell_check: ['I10', 'I20.9', 'I21.9', 'I25.1', 'I42.9', 'I46.9', 'I48.9', 'I49.5', 'I50.9', 'K21.9'] },
    { default: '', description: "Be a professional date of birth (DOB) extractor and extract the patient's date of birth in dd-mm-yyyy format. Example: '03-09-1997' for 3 September 1997. If it is not mentioned, leave it blank.", key: 'dob' },
    { default: '', description: "Type out the patient's name as they are referred to in the transcript. Example: 'Karl Koch'. If the transcript indicates that the person speaking spelled out the name, e.g., 'J-E-H-L-E.' the spelled-out version should then be used as the correct spelling of the name 'Jehle'.", key: 'patient_name', spell_check: ['van der Merwe', 'Vanlierde', 'du Toit', 'Botha', 'Koch', 'van Zyl', 'Naidoo', 'Pillay', 'Moodley', 'Khan', 'Mohamed', 'Ebrahim', 'Gopal', 'Greymond', 'Levengood', 'Maqungo', 'Kotze', 'Nell', 'Steel'] },
    { default: '', description: "Be a professional typist and extract and type out the name of the patient's medical aid mentioned, as well as their medical aid number if mentioned. Example: 'Polmed - 78043094'.", key: 'medical_aid', spell_check: ['Discovery Health', 'Bonitas', 'Momentum', 'Medihelp', 'Bestmed', 'Fedhealth', 'Polmed', 'Metropolitan', 'Medshield', 'GEMS', 'U.S. Medical Aid', 'CMP'] },
    { default: '', description: "The date of prescription in DD-MM-YYYY format. Example: '20-12-1997'.", from_profile: true, key: 'current_date' },
    { default: '', description: 'Be a professional typist for a general surgeon and list out each prescribed medication on a new line, starting with a number and period (e.g., \'1.\'). Take your time to ensure that the names of all medications are spelled correctly, as some may be misheard or mis-spelled by the underlying transcription software. IMPORTANT: Pay special attention to frequently misheard medications. Include the medication name, dosage, and frequency as and where mentioned in the transcript. Preserve all abbreviations and formatting. Example:\n1. Zyrtec 5mg BD p.r.\n2. Adalat 200mg daily p.r.', key: 'prescription', spell_check: ['Acarbose', 'Accenten', 'Adalat', 'Adco-Zolpidem', 'Alfuwin', 'Allopurinol', 'Altosec', 'Amycor', 'Arycor', 'Aspirin', 'Asperger', 'Aspavor', 'Atorvastatin', 'Azzalure', 'Bilocor', 'Bayers- Asprin', 'Bisoprolol', 'Cardicor', 'Cilift', 'Clopiwin', 'Co-ecodyne', 'Cosa Comp', 'Copalia', 'Cynt', 'Carzin XL', 'Coralan', 'Dabiklot', 'Dasit', 'Desperan Colio K', 'Diaglucide MR', 'Diaglucide MR instead of diabloside', 'Digoxin', 'Dominal', 'Donopezil', 'Dormonoct', 'Disprin', 'Disprin CV', 'Duforzig', 'Dupont', 'Ebastine', 'Ecotrin', 'Emcor', 'Esomegen', 'Eltroxin', 'Euthyrox', 'Exinef', 'Folic Acid', 'Furosemide', 'Glucophage XR', 'Galdus', 'Hexal', 'Hexarone', 'Imcord', 'Indapamide SR', 'Inspra', 'Ivabradine', 'Ivedal', 'iXarola', 'Jalra', 'Lasix', 'Lenditro', 'Lexamil', 'Levothyroxine', 'Loprazolam', 'Lomanor / Amlodopine', 'Losartan + HCTZ', 'mane', 'Melor', 'Mysoline', 'Migrobin', 'Nebivolol', 'Neurobion', 'nocte', 'Paracetamol', 'Pearinda', 'Pearinda, not Perinda', 'Peploc', 'Pericose', 'Plenish K', 'Potassium supplement', 'pravulan', 'Prexum Plus', 'prn', 'Pulmicort', 'Puricos', 'qid', 'Ramipril', 'Reaptan', 'Rezalto', 'Rosuvastatin', 'Revite SR', 'Sameuls', 'Sandoz Omeprazole', 'Serdip', 'Sertraline', 'Sideral Forte', 'Simvacor', 'Simvastatin', 'Slow-Mag', 'Spiractin', 'Stapran', 'stat', 'Stugeron', 'Sotahexal', 'Symbicort', 'Tambocor', 'tds', 'Telmisartan', 'Thiamine', 'thrice', 'Tramazac', 'Trazodone', 'Trustan', 'twice', 'Uromax', 'Vagifem', 'Verahexal', 'Vusor', 'Vymada', 'Warfarin', 'Xarelto', 'Xefo', 'Zartan', 'Zolpidem', 'Zuvamor', 'Zyquis', 'Zyrtec', 'Ciprofloxacin', 'Metronidazole', 'Amoxicillin', 'Diclofenac', 'Morphine', 'Ketorolac', 'Paracetamol', 'Pethidine', 'Tazocin', 'Ibuprofen', 'Tramadol', 'Ranitidine', 'Omeprazole', 'Pantoprazole', 'Aspirin', 'Loperamide', 'Hydrocodone', 'Codeine', 'Enoxaparin', 'Clopidogrel', 'Warfarin', 'Lignocaine', 'Bupivacaine', 'Ceftriaxone', 'Cefotaxime', 'Betadine', 'Atropine', 'Diazepam', 'Propofol', 'Thiopental', 'Fentanyl', 'Naloxone', 'Ondansetron'] },
  ]),
  mo('sick_note', 'Sick Note', [
    { default: '', description: 'Be a professional medical typist and extract this field based on the transcript in the exact style and format the doctor usually dictates. Populate with the full name and title of the patient (Mr./Mrs./Ms.), exactly as dictated by Dr. Mohamed Patel. Correct only minor grammar or punctuation if necessary. Example: \'Ms Thandi Mhlongo\'.', key: 'patient_name', spell_check: ['van der Merwe', 'du Toit', 'van Zyl', 'Naidoo', 'Pillay', 'Mhlongo', 'Moodley', 'Khan', 'Ebrahim', 'Govender'] },
    { default: '', description: 'Be a professional medical typist and extract this field based on the transcript in the exact style and format the doctor usually dictates. Populate with the date of examination in DD-MM-YYYY format. Example: \'22-10-2025\'.', key: 'date_of_exam' },
    { default: '', description: 'Be a professional medical typist and write the patient’s diagnoses exactly as dictated by Dr. Patel.  Do not use Python list format. Example:\n- Acute appendicitis \n- Type 2 diabetes mellitus \n- Post-operative wound infection', key: 'diagnoses', spell_check: ['appendicitis', 'diabetes', 'hypertension', 'cellulitis', 'haemorrhage', 'hernia', 'post-operative', 'infection', 'abscess', 'neoplasm'] },
    { default: '', description: 'Be a professional medical typist and extract this field based on the transcript in the exact style and format the doctor usually dictates. Populate with the date the patient’s period of sick leave begins, in DD/MM/YYYY format. Example: \'20/10/2025\'.', key: 'sick_start' },
    { default: '', description: 'Be a professional medical typist and extract this field based on the transcript in the exact style and format the doctor usually dictates. Populate with the date the patient’s period of sick leave ends, in DD/MM/YYYY format. Example: \'24/10/2025\'.', key: 'sick_end' },
    { default: '', description: 'Be a professional medical typist and extract this field based on the transcript in the exact style and format the doctor usually dictates. Populate with the date until which the patient is expected to perform amended duties or work in an adapted capacity, in DD/MM/YYYY format. Example: \'28/10/2025\'. Do not repeat sick leave dates here.', key: 'until' },
    { default: '', description: 'Be a professional medical typist and extract this field based on the transcript in the exact style and format the doctor usually dictates. Populate with the date the patient must return for follow-up, in DD/MM/YYYY format. Example: \'04/11/2025\'.', key: 'follow_up' },
    { default: '', description: 'Be a professional medical typist and extract this field based on the transcript in the exact style and format the doctor usually dictates. Populate with today’s date in DD/MM/YYYY format. Example: \'22/10/2025\'.', from_profile: true, key: 'current_date' },
  ]),
  mo('ward_dictation', 'Ward Dictation', [
    {
      default: '',
      description:
        'You are an intelligent medical typist for Dr. Patel. Take the dictation provided and transcribe it exactly word-for-word into a structured daily surgical follow-up note. Reproduce all introductory lines exactly as dictated (e.g., \'Today’s date is 25-05-2025 and the time is 12:07.\' followed by \'25th May 2025,\'). The dictation may cover multiple patients; whenever you encounter the phrase \'new patient,\' start a new patient section. \n\nFor each patient, transcribe all information under the following **ward round format headings**, laid out in blocks as below:\n\nSurname, Name: [Patient name]\nWard & Bed: [Ward/Bed location]\nDate of Birth: [DOB]\nID: [ID number]\n\nPrimary Surgeon: [Surgeon name]\nDiagnosis: [List all diagnoses, each with ICD10 code in brackets. If not dictated, insert the correct ICD10 from your knowledge.]\nOperation: [Operation/procedure if mentioned]\n\nMedical Aid: [Medical aid name]\nMedical Aid Number: [Number]\nContact Number: [Number]\n\nCurrent Condition:\n- Dictate patient progress, symptoms, clinical findings, drains, tubes, lines, etc., word-for-word.\n\nManagement Plan:\n- List all management steps exactly as dictated, using bullet points or numbered lists if spoken.\n\nEnsure no data from one patient appears under another. Spell all drug names, surgical terminology, and operative procedures correctly. Use numerals for all values (e.g., BP 147/80) and contract SI units to standard abbreviations (mm, cm, kg/m^2, L/min, mmol/L). Preserve dictated formatting such as new lines, bullet points, and numbering.\n\nYour goal is to produce a perfectly formatted ward round note document in this block style, capturing Dr. Patel’s rounds for each patient.',
      key: 'dictation',
      spell_check_terms: ['apyrexial', 'laparotomy', 'laparoscopy', 'laparoscopic', 'appendicectomy', 'colectomy', 'anastomosis', 'stoma', 'ileostomy', 'colostomy', 'drains', 'serous', 'haemoserous', 'haemorrhagic', 'purulent', 'Vicryl', 'PDS', 'Monocryl', 'Prolene', 'haemostasis', 'diathermy', 'LigaSure', 'Harmonic', 'Seprafilm', 'fascia', 'peritoneum'],
    },
  ]),
];
